[package]
name = "leek-ast"
version = "0.1.0"
edition = "2021"
toolchain = "nightly"

[dependencies]
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
miette = { version = "5.7", features = ["fancy"] }
